# Generated by Django 5.1.3 on 2024-12-06 17:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0012_data_repository_inclusion_chain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strain',
            name='name',
            field=models.CharField(blank=True, help_text='Standard descriptive name E.g. "C57BL/6J", http://www.informatics.jax.org/mgihome/nomen/', max_length=255),
        ),
        migrations.AlterField(
            model_name='subject',
            name='nickname',
            field=models.CharField(default='-', help_text='Please follow the standard format :\nTwo or three initials of the person in charge + number of the animal for that person, in chronological order.\ne.g. wm25 => Wilson Mena mouse n°25.\nFor following the identity of the mouses in term of genotype/injected viruses and the correspunding number in mayakind,\nplease use the Zygosities fields below, and the description field to put more details that you want to remember.', max_length=64, validators=[django.core.validators.RegexValidator('^[-._~\\+\\*\\w]+$', 'Nicknames must only contain letters, numbers, or any of -._~.')]),
        ),
    ]
