# Generated by Django 4.1.3 on 2023-06-13 13:00

from alyx.actions import models as action_models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("actions", "0021_migrating_narrative_markdown"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chronicrecording",
            name="narrative",
            field=action_models.SideBySideMarkdownxField(
                blank=True,
                help_text="All other details of the experiment you want to include, in a text format. "
                "(markdown capable)",
            ),
        ),
        migrations.AlterField(
            model_name="otheraction",
            name="narrative",
            field=action_models.SideBySideMarkdownxField(
                blank=True,
                help_text="All other details of the experiment you want to include, in a text format. "
                "(markdown capable)",
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="narrative",
            field=action_models.SideBySideMarkdownxField(
                blank=True,
                help_text="All other details of the experiment you want to include, in a text format. "
                "(markdown capable)",
            ),
        ),
        migrations.AlterField(
            model_name="surgery",
            name="narrative",
            field=action_models.SideBySideMarkdownxField(
                blank=True,
                help_text="All other details of the experiment you want to include, in a text format. "
                "(markdown capable)",
            ),
        ),
        migrations.AlterField(
            model_name="virusinjection",
            name="narrative",
            field=action_models.SideBySideMarkdownxField(
                blank=True,
                help_text="All other details of the experiment you want to include, in a text format. "
                "(markdown capable)",
            ),
        ),
        migrations.AlterField(
            model_name="waterrestriction",
            name="narrative",
            field=action_models.SideBySideMarkdownxField(
                blank=True,
                help_text="All other details of the experiment you want to include, in a text format. "
                "(markdown capable)",
            ),
        ),
    ]
