# Generated by Django 4.1.3 on 2023-06-14 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0017_data_repository_inclusion_chain"),
        ("actions", "0022_migrating_narrative_markdown"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="default_data_repository",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="data.datarepository"
            ),
        ),
    ]
