ALLOWED_HOSTS = [%%MACHINE_ALLOWED_HOSTS%%]

DEFAULT_LAB_NAME = "defaultlab"

SECRET_KEY = "%%DJANGO_SECRET_KEY%%"

NARRATIVE_TEMPLATES = {}

DBBACKUP_HOSTNAME = "%%DB_BACKUP_HOSTNAME%%"

TIME_ZONE = "%%TIMEZONE%%"
