# Generated by Django 5.1.3 on 2024-12-06 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '00012_create_role_readaccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='timezone',
            field=models.CharField(blank=True, default='Etc/UTC', help_text='Timezone of the server (see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones)', max_length=64),
        ),
    ]
