# Generated by Django 4.1.3 on 2023-06-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0020_removing_data_repository_from_filerecords'),
    ]

    operations = [
        migrations.AddField(
            model_name='filerecord',
            name='hash',
            field=models.CharField(blank=True, help_text='Hash of the data buffer, SHA-1 is 40 hex chars, while md5is 32 hex chars', max_length=64, null=True),
        ),
    ]
