# Generated by Django 4.1.3 on 2023-06-20 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0022_datasets_blank_allowed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataset",
            name="collection",
            field=models.CharField(blank=True, default="", help_text="file subcollection or subfolder", max_length=255),
        ),
    ]
